version: '3.8'
services:
  web:
    build: .
    ports:
    - "5002:5000"
    volumes:
    - .:/opt
    links:
    - mongo
    cap_add:
    - NET_ADMIN
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: siesta3
    volumes:
      - mongo-data:/data2/db
      - mongo-configdb:/data2/configdb


volumes:
  mongo-data:
    driver: local
  mongo-configdb:
